/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.pr.nb.sysprops.nodes;

import java.io.File;
import java.util.Arrays;

/**
 *
 * @author Mahakaal
 */
public class SplitRenderer extends javax.swing.JPanel {

    /**
     * Creates new form SplitRenderer
     */
    public SplitRenderer(String textValue) {
        initComponents();
        renderSplitText(textValue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(400, 300));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 300));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setPreferredSize(new java.awt.Dimension(400, 300));
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void renderSplitText(String textValue) {
        String [] rows = textValue.split(File.pathSeparator);
        StringBuilder contents = new StringBuilder(0);
        Arrays.asList(rows).forEach(row->contents.append(row).append("<br/>"));
        jTextPane1.setText(contents.toString());
    }
}
