/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.pr.nb.git;

import java.awt.Component;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.openide.awt.StatusLineElementProvider;
import org.openide.filesystems.FileObject;
import org.openide.modules.OnStart;
import org.openide.util.*;
import org.openide.util.lookup.ServiceProvider;

/**
 *
 * @author msivasub
 */
@OnStart
@ServiceProvider(service = StatusLineElementProvider.class, position = 3)
public class GitStatusPanel extends javax.swing.JPanel implements LookupListener, StatusLineElementProvider, Runnable{

    /**
     * Creates new form GitStatusPanel
     */
    private final Lookup lookupContext;
    Lookup.Result<FileObject> lookupInfo;
    public GitStatusPanel() {
        initComponents();
        lookupContext=Utilities.actionsGlobalContext();
        lookupInfo = lookupContext.lookupResult(FileObject.class);
        lookupInfo.addLookupListener(this);
        resultChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gitStatusLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(gitStatusLabel, org.openide.util.NbBundle.getMessage(GitStatusPanel.class, "GitStatusPanel.gitStatusLabel.text")); // NOI18N
        add(gitStatusLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gitStatusLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void resultChanged(LookupEvent lookupevent) {
        Collection< ? extends Lookup.Item<FileObject>> lookedUpInstance = lookupInfo.allItems();
        LOG.log(Level.INFO,"Found Looked up instances "+lookedUpInstance);
    }
    private static final Logger LOG = Logger.getLogger(GitStatusPanel.class.getName());

    @Override
    public Component getStatusLineElement() {
        return this;
    }

    @Override
    public void run() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
